#!/usr/bin/env bash
#
# Mechanical guard: no AI-attribution trailers in commit messages.
#
# The rule (RATIFIED 2026-09-13, no exceptions): a commit message body must not
# contain a line that is a `Co-Authored-By:` trailer — regardless of who is
# named — nor a `Claude-Session:` trailer. There is no allow-list: no carve-out
# for `dependabot[bot]`, none for human co-authors, none for any identity. An
# allow-list is a hole, and identity matching rots as model names change.
#
# Two properties are load-bearing. Each element of each has a named control in
# scripts/check-no-ai-trailers.test.sh that goes RED when that element alone is
# removed — the exact boundaries, not a blanket claim:
#
#   1. It matches a TRAILER, never PROSE. A guard that fires on prose gets
#      disabled within a week, and a disabled guard is worse than none. Two
#      separate elements produce that:
#        * the line-start anchor keeps a MID-LINE mention passing
#          ("...whether Co-Authored-By: lines are ever allowed") — control A11;
#        * the required colon keeps a line that STARTS with the phrase but is
#          prose passing ("Co-Authored-By trailers are banned") — control A13.
#      The historical false positive, a body reading "No Co-Authored-By. No
#      push.", is kept passing by BOTH (mid-line, and no colon) — control A10.
#   2. It scans only the commits under consideration — the message being
#      written, the commits being pushed, or merge-base..HEAD of a PR — never
#      full history. An upstream merge can import legitimate contributor
#      trailers at any time; a full-history check would then fail forever.
#      Controls C1 (PR scope passes over inherited history) and C2 (the same
#      history WOULD fail unscoped, so C1 is scoping and not luck).
#
# FAIL-CLOSED CONTRACT (every mode). A scan set this guard is unable to
# enumerate is REFUSED, never reported clean. `set -euo pipefail` does not see
# a failure inside `< <(...)` process substitution or inside `$(...)` used to
# feed a loop, so every such command has its status checked explicitly here.
# Controls FC1 (--range unresolvable), FC2 (--pre-push unknown remote oid),
# FC3 (--pre-push unknown local oid on a first push), FC4 (--commit
# unresolvable rev), FC5 (the scanner itself erroring), FC6 (the normalizer
# erroring), FC8 (--commit on an object that is not a commit), FC9 (the commit
# body read itself failing) and FC10 (git's null object id undeterminable).
#
# KNOWN RESIDUAL BYPASSES — stated because an undisclosed gap is worse than a
# disclosed one. Layers 1 and 2 are local hooks and are best-effort BY
# CONSTRUCTION. Layer 3 (CI) is the only layer that CAN bind a merge, and it
# does so only once an operator marks the `no-ai-trailers` job a required
# status check in branch protection; until that toggle is set it reports and
# does not block:
#
#   * `git commit --no-verify` / `git push --no-verify`, and `HUSKY=0`, skip
#     the local hooks. Layer 3 still scans the PR's commits.
#   * `$XDG_CONFIG_HOME/husky/init.sh` (default `~/.config/husky/init.sh`) is
#     `.`-sourced by `.husky/_/h` BEFORE its `HUSKY=0` check, so an `exit 0`
#     placed there silently disables every husky hook in every repository, with
#     nothing on the command line to show for it.
#   * `git config core.hooksPath <elsewhere>` repoints hooks wholesale.
#   * `.husky/_` is generated by `npm install` and ignores itself via
#     `.husky/_/.gitignore`; a fresh clone therefore has no local layers at all
#     until dependencies are installed.
#   * Upstream history imported by a merge is deliberately out of scope
#     (property 2 above).
#   * Layer 1 normalization boundary: a blank-indented trailer-shaped line
#     placed below BOTH git's literal cut line AND a literal `diff --git ` line
#     is not distinguishable from verbose-diff context, so layer 1 lets it
#     through. git does not parse such a line as a trailer. Layers 2 and 3 scan
#     the committed message with NO normalization and do refuse it — control S5
#     asserts exactly that, as a side effect (the remote ref does not move).
#   * Self-validation: the `guard-self-test` CI job runs the acceptance matrix
#     of the pull request it is checking, so one pull request can weaken the
#     predicate, the matrix and the workflow together and still go green.
#     .github/CODEOWNERS names an owner for those three paths; that entry only
#     binds once branch protection requires code-owner review, which is an
#     operator action outside this repository's tree.
#
# Usage:
#   check-no-ai-trailers.sh --message <file>   scan a prepared commit message
#   check-no-ai-trailers.sh --commit <rev>     scan one commit's message
#   check-no-ai-trailers.sh --range <range>    scan every commit in a range
#   check-no-ai-trailers.sh --pre-push <remote>  read git's pre-push stdin
#
# Exits 0 when clean, 1 when a forbidden trailer is found (naming the commit,
# the line number and the line) or when a scan set could not be enumerated,
# 2 on usage error.

set -euo pipefail

# ---------------------------------------------------------------------------
# THE PREDICATE. One definition, used by every mode and every layer.
#
# `^[[:blank:]]*` — anchored at line start, then optional leading blanks. The
# blanks are a deliberate widening of the ratified `^Co-Authored-By:`: strictly
# a superset (it blocks more, never less) that closes an indent-one-space
# evasion — control A7. `[[:blank:]]*:` likewise tolerates `Co-Authored-By :`.
# Matching is case-insensitive on the key (`-i` at every call site, control A5
# and A6). No identity is inspected: the rule has no allow-list, so there is
# nothing here to weaken per-identity.
#
# normalize_message() re-uses this SAME string, lower-cased by the shell, so
# the normalizer's "never drop a line that is itself a hit" rule can never
# drift from what the scanner looks for.
# ---------------------------------------------------------------------------
FORBIDDEN_TRAILER_RE='^[[:blank:]]*(Co-Authored-By|Claude-Session)[[:blank:]]*:'

# git's own scissors marker, byte-for-byte. `wt_status_locate_end()` in git
# builds the pattern as <comment char> + ' ' + this string and matches the
# WHOLE line, so this guard compares whole lines too — an 8-dashes-anywhere
# approximation matched shapes git keeps (see normalize_message).
GIT_CUT_LINE_BODY='------------------------ >8 ------------------------'

PROGRAM_NAME="$(basename "$0")"

usage() {
  cat >&2 <<EOF
usage: $PROGRAM_NAME --message <file>
       $PROGRAM_NAME --commit <rev>
       $PROGRAM_NAME --range <rev-range>
       $PROGRAM_NAME --pre-push <remote-name>   (reads git's pre-push stdin)
EOF
  exit 2
}

# Print the commit message with only the text GIT ITSELF removes removed.
#
# git's cleanup is mode-dependent and a commit-msg hook does not get told which
# mode is in force: `git commit -m` / `-F` runs cleanup=whitespace, where git
# keeps comment lines AND keeps any scissors-shaped line and everything under
# it; an editor commit runs cleanup=strip; only `git commit -v` (verified: the
# hook is handed the message WITH the diff still attached) and
# `--cleanup=scissors` on an edited message truncate at git's cut line. Because
# the mode is invisible here, this errs toward scanning MORE — two narrow drops,
# each of which is kept from hiding a real trailer:
#
#   * A comment line is dropped only when the line is not itself a hit for the
#     predicate. `core.commentChar` is user-configurable and git accepts a
#     letter: with `core.commentChar = C`, an unconditional comment rule would
#     treat `Co-Authored-By: ...` as commentary and swallow it. Control FC7
#     commits under exactly that config and asserts the commit is refused.
#   * The verbose diff is dropped only BELOW git's literal cut line (the
#     comment-prefixed form git writes and matches — an uncommented or
#     differently-dashed lookalike drops nothing, controls S1/S2/S3), only once
#     a `diff --git ` line has been seen below it, and only for blank-prefixed
#     unified-diff CONTEXT lines, which are the only diff shape the predicate
#     can match. A trailer at column 0 below a real cut line is still scanned —
#     control S4, because `-F` makes git keep it.
#
# The boundary this leaves open is stated in the KNOWN RESIDUAL BYPASSES block
# above and is pinned by control S5, not asserted away.
normalize_message() {
  local file="$1" comment_char cut_line
  comment_char="$(git config --get core.commentChar 2>/dev/null || true)"
  if [ -z "$comment_char" ] || [ "$comment_char" = "auto" ]; then
    comment_char='#'
  fi
  cut_line="$comment_char $GIT_CUT_LINE_BODY"
  awk -v cc="$comment_char" -v cut="$cut_line" -v re="${FORBIDDEN_TRAILER_RE,,}" '
    function is_hit(s) { return tolower(s) ~ re }
    !below && $0 == cut                              { below = 1; next }
    below && index($0, "diff --git ") == 1           { sawdiff = 1 }
    substr($0, 1, length(cc)) == cc && !is_hit($0)   { next }
    below && sawdiff && /^[[:blank:]]/               { next }
                                                     { print }
  ' "$file"
}

# Scan text on stdin. $1 is how the offender should be named in the report.
# Returns 1 and prints the offending line(s) when the predicate matches, and
# also returns 1 when the scan itself failed — grep exits >=2 on error, and
# swallowing that with `|| true` would report an unread stream as clean
# (control FC5).
scan_text() {
  local label="$1" hits='' rc=0
  hits="$(grep -n -i -E "$FORBIDDEN_TRAILER_RE")" || rc=$?
  if [ "$rc" -ge 2 ]; then
    echo "ERROR: could not scan $label (scanner exited $rc); refusing" >&2
    return 1
  fi
  [ -z "$hits" ] && return 0

  {
    echo "ERROR: forbidden AI-attribution trailer in $label"
    echo "$hits" | sed 's/^/  line /'
  } >&2
  return 1
}

scan_commit() {
  local rev="$1" sha subject body
  if ! sha="$(git rev-parse --verify --quiet "$rev^{commit}")"; then
    echo "ERROR: unable to resolve $rev to a commit; refusing rather than reporting it clean" >&2
    return 1
  fi
  subject="$(git show -s --format=%s "$sha" 2>/dev/null || true)"
  # The body read gets its OWN status check, and its own control (FC9). It is
  # NOT redundant with the resolve above: `git rev-parse` can succeed and the
  # message read still fail (a git that dies mid-read, an unreadable object).
  # Without this check `body` would be the empty string, `scan_text` would find
  # nothing in it, and a commit that really does carry `Co-Authored-By:` would
  # be reported CLEAN. Proven by the reviewer and now pinned: FC9 fails a
  # pass-through `git` stub on `--format=%B` alone and asserts this refusal.
  if ! body="$(git show -s --format=%B "$sha")"; then
    echo "ERROR: unable to read the message of $sha; refusing rather than reporting it clean" >&2
    return 1
  fi
  printf '%s\n' "$body" | scan_text "commit $sha (\"$subject\")"
}

scan_range() {
  local range="$1" rev failed=0 revs
  # `git rev-list` on an empty or already-merged range emits nothing: a PR with
  # no new commits is clean, not an error. A rev-list that FAILS is a different
  # thing entirely, and the status has to be checked here — feeding the loop
  # from an unchecked `$(...)` would turn "could not enumerate" into "nothing to
  # scan", i.e. a pass (control FC1).
  if ! revs="$(git rev-list "$range")"; then
    echo "ERROR: unable to enumerate the commits in range $range; refusing the scan" >&2
    return 1
  fi
  while read -r rev; do
    [ -z "$rev" ] && continue
    scan_commit "$rev" || failed=1
  done <<<"$revs"
  return "$failed"
}

# git's pre-push protocol: one `<local_ref> <local_oid> <remote_ref>
# <remote_oid>` line per ref being pushed, on stdin.
scan_pre_push() {
  # $1 is the remote name or URL git passes to the hook; it is not used for
  # scoping (see below) but is part of the hook contract.
  local zero local_ref local_oid remote_ref remote_oid
  local rev failed=0 revs

  # Control FC10. What this check buys is narrower than the others and is
  # stated as such: with it removed the guard does NOT fail open on a trailer
  # — `$zero` becomes the empty string, no ref line matches it, and every line
  # is then handed to `git rev-list`, which refuses a deletion or a first push
  # because the null oid is not a resolvable rev. What it does buy is that a
  # push git could not even be classified for is refused deliberately, with a
  # diagnostic naming the real fault, instead of being allowed whenever the
  # range happens to resolve. FC10 asserts exactly that difference (refused vs
  # accepted on an otherwise clean range) and goes RED when this check alone is
  # removed.
  if ! zero="$(git hash-object --stdin </dev/null | tr '0-9a-f' '0')" || [ -z "$zero" ]; then
    echo "ERROR: unable to determine git's null object id; refusing the push" >&2
    return 1
  fi

  while read -r local_ref local_oid remote_ref remote_oid; do
    [ -z "${local_oid:-}" ] && continue
    # Branch deletion: nothing to scan.
    [ "$local_oid" = "$zero" ] && continue

    if [ "$remote_oid" = "$zero" ]; then
      # First push of a branch: scan every commit that is not already on a
      # remote-tracking ref. Anything excluded here either arrived by fetch
      # (upstream history, which this guard deliberately does not police) or
      # was itself scanned by the push that published it. Scanning from the
      # root instead would re-scan all of upstream on every new branch.
      if ! revs="$(git rev-list "$local_oid" --not --remotes)"; then
        echo "ERROR: unable to enumerate the commits being pushed to ${remote_ref:-?}; refusing the push" >&2
        failed=1
        continue
      fi
    else
      if ! revs="$(git rev-list "$remote_oid..$local_oid")"; then
        echo "ERROR: unable to enumerate ${remote_oid}..${local_oid}; refusing the push" >&2
        failed=1
        continue
      fi
    fi

    while read -r rev; do
      [ -z "$rev" ] && continue
      scan_commit "$rev" || failed=1
    done <<<"$revs"
  done

  return "$failed"
}

print_fix_hint() {
  cat >&2 <<'EOF'

The no-AI-trailer rule has no exceptions: no `Co-Authored-By:` line (whoever is
named) and no `Claude-Session:` line may appear in a commit message.

To fix:
  * most recent commit   ->  git commit --amend           (delete the line)
  * an older commit      ->  git rebase -i <base>         (reword it)
  * while writing one    ->  remove the trailer and commit again

If instead this run could not enumerate what to scan, fix the repository state
(fetch the missing objects, correct the range) and run again: refusing is
deliberate, because reporting an unscanned range as clean is the worse failure.

Do not bypass with --no-verify: the same check runs in CI over the pull
request's own commits, and once that job is a required status check it blocks
the merge as well.
EOF
}

main() {
  [ "$#" -ge 1 ] || usage

  local status=0 normalized
  case "$1" in
    --message)
      [ "$#" -eq 2 ] || usage
      [ -f "$2" ] || { echo "ERROR: no such message file: $2" >&2; exit 2; }
      if ! normalized="$(normalize_message "$2")"; then
        echo "ERROR: unable to read the commit message file $2; refusing" >&2
        status=1
      else
        printf '%s\n' "$normalized" | scan_text "the commit message being written" || status=1
      fi
      ;;
    --commit)
      [ "$#" -eq 2 ] || usage
      scan_commit "$2" || status=1
      ;;
    --range)
      [ "$#" -eq 2 ] || usage
      scan_range "$2" || status=1
      ;;
    --pre-push)
      scan_pre_push || status=1
      ;;
    -h | --help)
      usage
      ;;
    *)
      usage
      ;;
  esac

  [ "$status" -eq 0 ] && return 0
  print_fix_hint
  return 1
}

main "$@"
